version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/scripts/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tokenized_llm_finance"
    schedule:
      interval: "weekly"
