name: PowerShell Scripts Test

on:
  push:
  pull_request:

jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse PowerShell scripts
        shell: pwsh
        run: |
          Get-ChildItem -Path './scripts/powershell' -Recurse -Include *.ps1,*.psm1,*.psd1 | ForEach-Object {
            $tokens = $null
            $errors = $null
            [System.Management.Automation.Language.Parser]::ParseFile($_.FullName, [ref]$tokens, [ref]$errors) | Out-Null
            if ($errors.Count -gt 0) {
              $errors | ForEach-Object { Write-Error "$($_.Extent.File):$($_.Extent.StartLineNumber): $($_.Message)" }
            }
          }
      - name: Run shellcheck
        run: shellcheck scripts/linux/*.sh
        continue-on-error: true

  test-scripts:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Parse PowerShell scripts
        shell: pwsh
        run: |
          Get-ChildItem -Path './scripts/powershell' -Recurse -Include *.ps1,*.psm1,*.psd1 | ForEach-Object {
            $tokens = $null
            $errors = $null
            [System.Management.Automation.Language.Parser]::ParseFile($_.FullName, [ref]$tokens, [ref]$errors) | Out-Null
            if ($errors.Count -gt 0) {
              $errors | ForEach-Object { Write-Error "$($_.Extent.File):$($_.Extent.StartLineNumber): $($_.Message)" }
            }
          }
