name: PowerShell Scripts Test

on:
  push:
  pull_request:

jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        pwsh -Command Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    - name: Run shellcheck
      run: shellcheck scripts/linux/*.sh
    - name: Run PSScriptAnalyzer
      shell: pwsh
      run: Invoke-ScriptAnalyzer -Path './scripts/powershell' -Recurse -ErrorAction Stop

  test-scripts:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run DiskUsageReport
      shell: pwsh
      run: ./scripts/powershell/DiskUsageReport.ps1
    - name: Run Get-SystemInfo
      shell: pwsh
      run: ./scripts/powershell/Get-SystemInfo.ps1
    - name: Test ManageServices status
      shell: pwsh
      run: ./scripts/powershell/ManageServices.ps1 -Action status -ServiceName spooler
    - name: List local users
      shell: pwsh
      run: ./scripts/powershell/UserManagement.ps1 -Action list
    - name: Test VMManagement list
      shell: pwsh
      run: ./scripts/powershell/VMManagement.ps1 -Action list
