name: PowerShell Scripts Test

on:
  push:
  pull_request:

jobs:
  test-scripts:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run DiskUsageReport
      shell: pwsh
      run: ./scripts/powershell/DiskUsageReport.ps1
    - name: Run Get-SystemInfo
      shell: pwsh
      run: ./scripts/powershell/Get-SystemInfo.ps1
    - name: Test ManageServices status
      shell: pwsh
      run: ./scripts/powershell/ManageServices.ps1 -Action status -ServiceName spooler
    - name: List local users
      shell: pwsh
      run: ./scripts/powershell/UserManagement.ps1 -Action list
    - name: Test VMManagement list
      shell: pwsh
      run: ./scripts/powershell/VMManagement.ps1 -Action list
