name: PowerShell Scripts Test

on:
  push:
  pull_request:

jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse PowerShell scripts
        shell: pwsh
        run: ./scripts/powershell/Test-ScriptSyntax.ps1 -Path ./scripts/powershell
      - name: Run shellcheck
        run: shellcheck scripts/linux/*.sh
        continue-on-error: true

  test-scripts:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Parse PowerShell scripts
        shell: pwsh
        run: ./scripts/powershell/Test-ScriptSyntax.ps1 -Path ./scripts/powershell
